import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { FavoritesContextProvider } from "@/context/FavoritesContext";
import { ReservationContextProvider } from "@/context/ReservationContext";
import Providers from "./Providers";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <FavoritesContextProvider>
          <ReservationContextProvider >
             {children}
          </ReservationContextProvider>
         
          <Footer/>
        </FavoritesContextProvider>
        </Providers>
        <SpeedInsights />
      </body>
    </html>
  );
}


